### ISSUE TITLE
Extension icon is not visible in dark themes

### ISSUE THREAD

**Issue by arunrdd** [chinnichaitanya/IncognitoThis#1]

**Comment by chinnichaitanya** [comment]
Thank you for raising this @arnrdy! 😀

Thanks to @krishnakireeti for the new logo which works both in dark and light versions of the browser. 
Reference: https://github.com/chinnichaitanya/IncognitoThis/commit/5adf19cf9d1748d2cecdb067ded45cf90429bcff and https://github.com/chinnichaitanya/IncognitoThis/commit/7298109bea199d81e6895f477d5df42aee9e5984

Closing this issue. It will be reflected in the next release! 🎉
